class Data:
    dcsl_data = {'pages_dict': {'115349': {'children__len': 6,
                           'contents': {'en': {'boxes': [{'content_50chars': '<div><img width="651" height="235" src="/files/Servers lab pic.jpg?uuid=default:c7f6d830-bd42-4843-bcc8-d7e817744dc3" alt="" /></div> ', 'title': '', 'type': 'text'},
                                                         {'content_50chars': '<ul>  <li>   <h4>IX -- a specialized operating system for datacenter applications</h4>  </li>  <li>   <h4>soNUMA -- rack-scale computing</h4>  </li>  ',
                                                          'title': 'Projects',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p><strong>We would like to thank our sponsors for their support</strong></p> <p>&nbsp;</p> <p>&nbsp;<img width="107" height="61" border="5" alt="" st',
                                                          'title': '',
                                                          'type': 'text'}],
                                               'language': 'en',
                                               'last_update': datetime.datetime(2017, 5, 19, 15, 47, 23),
                                               'path': '/index.html',
                                               'sidebar__boxes': [{'content_50chars': '', 'title': 'Prof. Edouard Bugnion', 'type': "unknown 'epfl:home'"}],
                                               'title': 'DCSL'}},
                           'contents__keys': dict_keys(['en']),
                           'level': 0,
                           'pid': '115349',
                           'template': 'home'},
                '115407': {'children__len': 0,
                           'contents': {'en': {'boxes': [{'content_50chars': '[infoscience url=http://infoscience.epfl.ch/curator/export/9665/?ln=en]', 'title': '', 'type': 'infoscience'}],
                                               'language': 'en',
                                               'last_update': datetime.datetime(2016, 8, 8, 16, 31, 41),
                                               'path': '/page-115407-en.html',
                                               'sidebar__boxes': [{'content_50chars': '', 'title': 'Prof. Edouard Bugnion', 'type': "unknown 'epfl:home'"}],
                                               'title': 'Publications'}},
                           'contents__keys': dict_keys(['en']),
                           'level': 1,
                           'pid': '115407',
                           'template': 'simple'},
                '125741': {'children__len': 0,
                           'contents': {'en': {'boxes': [{'content_50chars': '<p><img alt="Edouard Bugnion" src="/files/Staff/Edouard Bugnion 2015.jpg?uuid=default:29c40c6f-8e18-4a6c-8ce8-094d218d16dd" style="float: left; margin',
                                                          'title': 'Prof. Edouard Bugnion',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p><img alt="" border="5" height="133" src="/files/Staff/Jonas Fietz.jpg?uuid=default:73dc52fd-0541-4295-ac2a-548453741ec0" style="float: left; margin',
                                                          'title': 'Jonas Fietz',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p><img alt="" style="float: left; margin: 5px;" src="/files/Staff/Marios Kogias.jpg?uuid=default:9783b418-413c-40da-b85a-ad4aceb7d75d" height="118" w',
                                                          'title': 'Marios Kogias',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p>  <!--[if gte mso 9]><xml>   <o:OfficeDocumentSettings>   <o:AllowPNG />   </o:OfficeDocumentSettings>   </xml><![endif]--> </p> <p>  <!--[if gte m',
                                                          'title': 'Stanko Novakovic',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p><img alt="" style="margin: 5px; float: left;" src="/files/Staff/Georges Prekas 2015.jpg?uuid=default:1958ca70-c2ab-4e59-97f3-19aabf2d0610" height="',
                                                          'title': 'George Prekas',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p><img src="/files/Staff/mia.jpg?uuid=default:adf9e713-b8fc-4bb0-ab07-74ffcaca0284" style="margin: 5px; float: left;" alt="" height="130" width="110"',
                                                          'title': 'Mia Primorac',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p><img width="101" height="135" border="5" alt="" style="float: left; margin: 5px;" src="/files/Staff/Dmitrii Ustiugov.jpg?uuid=default:d0f2abd0-9d40',
                                                          'title': 'Dmitrii Ustiugov  ',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p><img alt="" style="margin: 5px; float: left;" src="/files/Staff/Sam Whitlock 2015a.jpeg?uuid=default:28581c9d-2cb4-4e26-9de0-73d2927d223a" height="',
                                                          'title': 'Sam Whitlock',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p><img alt="" src="/files/Staff/margaret escandari church.jpg?uuid=default:814f3c68-0c45-4368-994d-8138a8e4aa32" style="margin: 5px; float: left;" he',
                                                          'title': 'Margaret Escandari',
                                                          'type': 'text'}],
                                               'language': 'en',
                                               'last_update': datetime.datetime(2017, 6, 7, 16, 24, 48),
                                               'path': '/page-125741-en.html',
                                               'sidebar__boxes': [{'content_50chars': '', 'title': 'Prof. Edouard Bugnion', 'type': "unknown 'epfl:home'"}],
                                               'title': 'Team'}},
                           'contents__keys': dict_keys(['en']),
                           'level': 1,
                           'pid': '125741',
                           'template': 'simple'},
                '126135': {'children__len': 0,
                           'contents': {'en': {'boxes': [{'content_50chars': '<h4><strong><br />  </strong><strong>Courses 2016 - 2017</strong> </h4> <p>&nbsp;</p> <p>  <a href="http://isa.epfl.ch/imoniteur_ISAP/!itffichecours.h',
                                                          'title': '',
                                                          'type': 'text'}],
                                               'language': 'en',
                                               'last_update': datetime.datetime(2017, 3, 9, 15, 12, 56),
                                               'path': '/page-126135-en.html',
                                               'sidebar__boxes': [{'content_50chars': '', 'title': 'Prof. Edouard Bugnion', 'type': "unknown 'epfl:home'"}],
                                               'title': 'Teaching'}},
                           'contents__keys': dict_keys(['en']),
                           'level': 1,
                           'pid': '126135',
                           'template': 'simple'},
                '126290': {'children__len': 0,
                           'contents': {'en': {'boxes': [{'content_50chars': '<p><strong>Scale-out NUMA (soNUMA</strong>) is a high-performance rack-scale system for scale-out analytics and data serving. Each soNUMA server relie',
                                                          'title': '',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p><img width="611" height="240" border="5" alt="" style="float: left; margin: 5px;" src="/files/sonuma1.png?uuid=default:aad25c7d-c6f6-4685-bff8-a26f',
                                                          'title': '',
                                                          'type': 'text'}],
                                               'language': 'en',
                                               'last_update': datetime.datetime(2016, 8, 8, 17, 36, 55),
                                               'path': '/page-126290-en.html',
                                               'sidebar__boxes': [{'content_50chars': '', 'title': 'Prof. Edouard Bugnion', 'type': "unknown 'epfl:home'"}],
                                               'title': 'soNUMA'}},
                           'contents__keys': dict_keys(['en']),
                           'level': 1,
                           'pid': '126290',
                           'template': 'simple'},
                '126292': {'children__len': 0,
                           'contents': {'en': {'boxes': [{'content_50chars': '<div>&nbsp;</div> <div>IX is an open-source project available at <a href="https://github.com/ix-project"><strong>ix-project</strong></a><br />  <br />',
                                                          'title': '',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p>&nbsp;<img width="535" height="394" border="5" src="/files/ix-architecture.jpg?uuid=default:968f6b2f-8a7b-4c81-83d8-3b15aff8838c" style="float: lef',
                                                          'title': '',
                                                          'type': 'text'},
                                                         {'content_50chars': '<p>Prekas, George; Belay, Adam; Primorac, Mia; Klimovic, Ana; Grossman, Samuel; Kogias, Marios; G&uuml;termann, Bernard; Kozyrakis, Christos; Bugnion,',
                                                          'title': '',
                                                          'type': 'text'}],
                                               'language': 'en',
                                               'last_update': datetime.datetime(2016, 8, 8, 17, 36, 58),
                                               'path': '/page-126292-en.html',
                                               'sidebar__boxes': [{'content_50chars': '', 'title': 'Prof. Edouard Bugnion', 'type': "unknown 'epfl:home'"}],
                                               'title': 'IX Dataplane Operating System'}},
                           'contents__keys': dict_keys(['en']),
                           'level': 1,
                           'pid': '126292',
                           'template': 'simple'},
                '145099': {'children__len': 0,
                           'contents': {'en': {'boxes': [{'content_50chars': '<h4>Low-Latency measuring client</h4> <p>Latency is defined as the time it takes a system to respond. In datacenter applications with complex communic',
                                                          'title': 'Master Thesis',
                                                          'type': 'text'},
                                                         {'content_50chars': '<h4>Evaluation of the QUIC protocol (Master)</h4> <p>QUIC is a new experimental transport protocol implemented by Google trying to overcome some of th',
                                                          'title': 'Semester Projects',
                                                          'type': 'text'}],
                                               'language': 'en',
                                               'last_update': datetime.datetime(2017, 5, 24, 15, 13, 1),
                                               'path': '/page-145099-en.html',
                                               'sidebar__boxes': [{'content_50chars': '', 'title': 'Prof. Edouard Bugnion', 'type': "unknown 'epfl:home'"}],
                                               'title': 'Master & Semester Projects'}},
                           'contents__keys': dict_keys(['en']),
                           'level': 1,
                           'pid': '145099',
                           'template': 'simple'}},
 'properties': {'acronym': 'DCSL',
                'base_path': 'build/dcsl',
                'breadcrumb_title': 'IC',
                'breadcrumb_url': 'http://ic.epfl.ch',
                'css_url': '//static.epfl.ch/v0.23.0/styles/ic-built.css',
                'export_files': {'en': 'build/dcsl/export_en.xml'},
                'files__len': 27,
                'homepage__pid': '115349',
                'name': 'dcsl',
                'pages__ids': ['115349', '125741', '126135', '145099', '115407', '126290', '126292'],
                'theme': 'ic',
                'title': 'Data Center Systems Laboratory'}}